'use client';

import { Calendar, Clock, ArrowRight, BookOpen, Cpu, Code, Zap } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';
import NewsletterSignup from '../components/NewsletterSignup';
import ContentModal from '../components/ContentModal';

const blogPosts = [
  {
    id: 'mcp-server-guide',
    title: 'Building Production-Ready MCP Servers: A Complete Guide',
    excerpt: 'Learn how to create robust Model Context Protocol servers that integrate seamlessly with AI platforms like Claude and ChatGPT.',
    author: 'Eugene Boondock',
    date: '2025-01-15',
    readTime: '8 min read',
    category: 'AI Integration',
    featured: true,
    image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop&crop=center'
  },
  {
    id: 'ai-accelerated-development',
    title: 'How AI Tools Are Revolutionizing Web Development Speed',
    excerpt: 'Discover how modern AI tools can reduce development time from months to weeks while maintaining code quality and scalability.',
    author: 'Eugene Boondock',
    date: '2025-01-10',
    readTime: '6 min read',
    category: 'AI & Development',
    featured: false,
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop&crop=center'
  },
  {
    id: 'earth2-platform-case-study',
    title: 'Building Earthie: A Comprehensive Earth2 Metaverse Analytics Platform Case Study',
    excerpt: 'Deep dive into creating a comprehensive Earth2 community platform with 13 specialized hubs, 17+ API integrations, AI-powered analytics, real-time data processing, and advanced mapping features. Learn about the technical challenges, architectural decisions, and innovative solutions implemented.',
    author: 'Eugene Boondock',
    date: '2025-01-05',
    readTime: '15 min read',
    category: 'Case Studies',
    featured: true,
    image: '/earthie-world.png'
  },
  {
    id: 'modern-backend-architecture',
    title: 'Modern Backend Architecture for Scalable Applications',
    excerpt: 'Best practices for building backend systems that can handle growth, using AWS services, database optimization, and microservices patterns.',
    author: 'Eugene Boondock',
    date: '2025-01-01',
    readTime: '10 min read',
    category: 'Backend Development',
    featured: false,
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop&crop=center'
  },
  {
    id: 'oauth-integration-patterns',
    title: 'OAuth 2.0 Integration Patterns for Multi-Platform Apps',
    excerpt: 'Comprehensive guide to implementing secure OAuth flows across different platforms and handling token management at scale.',
    author: 'Eugene Boondock',
    date: '2024-12-28',
    readTime: '7 min read',
    category: 'Authentication',
    featured: false,
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop&crop=center'
  },
  {
    id: 'debugging-complex-systems',
    title: 'Debugging Complex Distributed Systems: A Developer\'s Toolkit',
    excerpt: 'Essential techniques and tools for debugging microservices, API integrations, and distributed systems effectively.',
    author: 'Eugene Boondock',
    date: '2024-12-25',
    readTime: '9 min read',
    category: 'Development',
    featured: false,
    image: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=400&h=250&fit=crop&crop=center'
  },
  {
    id: 'debugging-ai-written-code',
    title: 'Debugging AI-Written Code',
    excerpt: 'Learn how to effectively debug code generated by AI tools, ensuring reliability and maintaining code quality in AI-assisted development.',
    author: 'Eugene Boondock',
    date: '2024-12-20',
    readTime: '8 min read',
    category: 'AI & Development',
    featured: false,
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=250&fit=crop&crop=center'
  }
];

const categories = ['All', 'AI Integration', 'AI & Development', 'Case Studies', 'Backend Development', 'Authentication', 'Development'];

export default function BlogPage() {
  const [selectedPost, setSelectedPost] = useState<typeof blogPosts[0] | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const openModal = (post: typeof blogPosts[0]) => {
    setSelectedPost(post);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setSelectedPost(null);
  };
  return (
    <main className="flex min-h-screen flex-col items-center justify-start pb-24">
      {/* Hero Section */}
      <section className="w-full pt-24 sm:pt-32 px-4 flex justify-center mb-16">
        <div className="max-w-4xl w-full text-center">
          <div className="flex items-center justify-center mb-6">
            <div className="p-4 bg-gradient-to-br from-orange-600 to-orange-400 rounded-2xl mr-4 shadow-lg">
              <BookOpen className="h-12 w-12 text-white" />
            </div>
            <h1 className="text-4xl sm:text-5xl font-extrabold accent">Technical Blog</h1>
          </div>
          <p className="text-xl text-black mb-4 max-w-3xl mx-auto">
            Insights on AI integration, web development, and building complex digital platforms
          </p>
          <p className="text-base text-zinc-700 max-w-2xl mx-auto">
            Sharing knowledge from real-world projects, AI tool experiences, and lessons learned in modern software development.
          </p>
        </div>
      </section>

      {/* Featured Post */}
      <section className="w-full px-4 flex justify-center mb-16">
        <div className="max-w-6xl w-full">
          <h2 className="text-2xl font-bold accent mb-8 text-center">Featured Article</h2>
          <div className="glass shadow-xl p-8 border border-orange-900/20">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
              <div className="relative h-64 lg:h-80 rounded-xl overflow-hidden">
                <Image
                  src="/earthie-world.png"
                  alt="Earthie Platform Case Study"
                  fill
                  className="object-cover transition-all hover:scale-105"
                />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <span className="px-3 py-1 bg-orange-100 text-orange-800 rounded-full text-sm font-medium">Case Studies</span>
                  <span className="px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm font-medium">Featured</span>
                </div>
                <h3 className="text-2xl font-bold accent mb-4">
                  Building Earthie: A Complex Metaverse Platform Case Study
                </h3>
                <p className="text-base text-zinc-700 mb-4 leading-relaxed">
                  Deep dive into creating a comprehensive Earth2 community platform with 17+ API integrations, real-time data processing, and advanced mapping features. Learn about the technical challenges and solutions implemented.
                </p>
                <div className="flex items-center gap-4 mb-6 text-sm text-zinc-600">
                  <div className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    December 5, 2024
                  </div>
                  <div className="flex items-center gap-1">
                    <Clock className="h-4 w-4" />
                    12 min read
                  </div>
                </div>
                <button
                  onClick={() => openModal(blogPosts.find(post => post.id === 'earth2-platform-case-study')!)}
                  className="btn-primary px-6 py-3 !text-white !bg-[#d17927] hover:!bg-orange-700 transition-all inline-flex items-center"
                >
                  Read Full Article <ArrowRight className="ml-2 h-4 w-4" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* All Posts */}
      <section className="w-full px-4 flex justify-center">
        <div className="max-w-6xl w-full">
          <h2 className="text-2xl font-bold accent mb-8">Latest Articles</h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {blogPosts.filter(post => !post.featured).map((post) => (
              <article key={post.id} className="glass shadow-lg p-6 border border-orange-900/20 hover:shadow-xl transition-all group">
                <div className="relative h-48 mb-4 overflow-hidden rounded-lg">
                  <Image
                    src={post.image}
                    alt={post.title}
                    fill
                    className="object-cover transition-all group-hover:scale-105"
                  />
                </div>

                <div className="mb-3">
                  <span className="px-2 py-1 bg-orange-100 text-orange-800 rounded-full text-xs font-medium">
                    {post.category}
                  </span>
                </div>

                <h3 className="text-lg font-bold accent mb-3 group-hover:text-orange-700 transition-colors">
                  {post.title}
                </h3>

                <p className="text-sm text-zinc-700 mb-4 leading-relaxed">
                  {post.excerpt}
                </p>

                <div className="flex items-center justify-between text-xs text-zinc-600">
                  <div className="flex items-center gap-3">
                    <span>{post.author}</span>
                    <div className="flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {new Date(post.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </div>
                  </div>
                  <div className="flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {post.readTime}
                  </div>
                </div>

                <button
                  onClick={() => openModal(post)}
                  className="mt-4 text-sm font-medium text-orange-600 hover:text-orange-700 transition-colors flex items-center group-hover:translate-x-1 transition-transform"
                >
                  Read more <ArrowRight className="ml-1 h-3 w-3" />
                </button>
              </article>
            ))}
          </div>

          {/* Newsletter CTA */}
          <div className="mt-16">
            <NewsletterSignup
              title="Stay Updated"
              description="Get notified when I publish new articles about AI integration, web development, and building complex digital platforms."
              variant="hero"
            />
          </div>
        </div>
      </section>

      {/* Modal */}
      <ContentModal
        content={selectedPost ? { ...selectedPost, type: 'blog' as const } : null}
        isOpen={isModalOpen}
        onClose={closeModal}
      />
    </main>
  );
}
